### ISSUE TITLE
Add hiking trails

### ISSUE THREAD

**Issue by sommergeo** [sommergeo/echaz-histo#3]
- Convert GPX/KML to geojson from [Remmsele](https://www.schwaebischealb.de/touren/immer-dem-remmsele-nach-der-pfullinger-sagenweg)
- Integrate vector lines from [OSM](https://download.geofabrik.de) data that represent these hiking trails from the [municipal homepage](https://www.pfullingen.de/ausflugsziele)
- Beschilderte Wanderwege: [waymarkedtrails.org](https://hiking.waymarkedtrails.org/#?map=13!48.4552!9.2633) (Dieser Datensatz muss erstmal nicht eingebaut werden, aber ich nenne ihn hier zur vollständigen Quellensammlung)

**Comment by m4rtin89** [comment]
Ich habe via Geofabrik noch Reit- und Fußwege, leider gibt es dort nicht die Rubrik Wanderwege, weshalb ich diese dann mit oben gezeigten abgleichen würde. Oder sollen/reichen ausschließlich die Wanderwege?

**Comment by AndyBraun** [comment]
Fußwege könnten interessant sein, sind allerdings oft auch sehr feinmaschig (zu detailliert?) 
Wenn es ein paar Zusatzwege sind, die die Wanderwege verbinden (z.B. für Abkürzungen), dann würd ich es reinnehmen, aber wenn jeder Trampelpfad drin ist und das Kartenbild nur unruhig macht, dann würd ich sie eher rauslassen.

**Comment by sommergeo** [comment]
Ich finde es am einfachsten, erstmal die drei Wanderwege (Sagenweg + Schönbergturm + Ursulaberg) auf der [Homepage](https://www.pfullingen.de/ausflugsziele) aus OSM-Daten zu selektieren und einzubauen.
- Andere Wanderwege/Reitwege sind ja schon in den Hintergrundkarten enthalten
- Die Wanderege der Homepage sind relativ "hochwertig", da sie über Stationen mit Infos und Kunstwerken (+[Beschreibung](https://www.pfullingen.de/de/entdecken-erholen/Ausflugsziele/Ausflugsziel?view=publish&item=tripDestination&id=1003) +[PDF](https://www.pfullingen.de/ceasy/resource/?id=7222&download=0)) verfügen und deswegen hervorhebenswert sind
- Wenn OSM-Daten als Grundlage verwendet werden, sind zumindest die OSM-Hintergrundkarten und der Overlay lageidentisch, im Gegensatz zu dieser Kombination auf deren [Webkarte](https://www.pfullingen.de/ceasy/sat/?sidebar=0&items=tripDestination):
![image](https://user-images.githubusercontent.com/26389306/72421909-b37f6180-3781-11ea-937e-e63c1cfe085c.png)

**Comment by m4rtin89** [comment]
Sagenweg (alias Remmsele) und Schönbergturm (als Wanderweg) sind in "data" "Geojson". Ursulaberg ist leider nicht so einfach, ich versuche die einzelnen Teilstücke via OSM "nach zu zeichen", aber das funktioniert alles nur dürftig. Ich bin dran.
